###
GET http://localhost:4000/test

###
GET http://localhost:4000/jobs

###
POST http://localhost:4000/jobs
content-type: application/json

{"jobtitle":"Test Ops 2","company":"Roncal Ltd","region":"Cardiff","jobcategory":"IT"}


###


PUT http://localhost:4000/jobs/1
content-type: application/json

{"jobTitle":"Test Ops","company":"XYZ Ltd","region":"West","jobCategory":"Accounting"}


###


DELETE http://localhost:4000/jobs/2